
-- 1. 기존 테이블이 존재하면 삭제하고 새로운 구조로 생성합니다.
DROP TABLE IF EXISTS job_character_assets;
CREATE TABLE job_character_assets (
  id SERIAL PRIMARY KEY,
  job_name VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  riasec_code VARCHAR(10),
  level INT NOT NULL,
  title_name VARCHAR(100) NOT NULL,
  image_url TEXT NOT NULL
);

-- 2. 데이터 삽입
INSERT INTO job_character_assets (job_name, category, riasec_code, level, title_name, image_url) VALUES
('성우', '예술형(A)', 'A', 1, '브론즈성우', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/actor_ari/lv1.png'),
('성우', '예술형(A)', 'A', 2, '실버성우', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/actor_ari/lv2.png'),
('성우', '예술형(A)', 'A', 3, '골드성우', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/actor_ari/lv3.png'),
('성우', '예술형(A)', 'A', 4, '다이아성우', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/actor_ari/lv4.png'),
('성우', '예술형(A)', 'A', 5, '마스터성우', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/actor_ari/lv5.png'),
('작곡가', '예술형(A)', 'A', 1, '브론즈작곡가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/composer_ari/lv1.png'),
('작곡가', '예술형(A)', 'A', 2, '실버작곡가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/composer_ari/lv2.png'),
('작곡가', '예술형(A)', 'A', 3, '골드작곡가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/composer_ari/lv3.png'),
('작곡가', '예술형(A)', 'A', 4, '다이아작곡가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/composer_ari/lv4.png'),
('작곡가', '예술형(A)', 'A', 5, '마스터작곡가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/composer_ari/lv5.png'),
('콘텐츠크리에이터', '예술형(A)', 'A', 1, '브론즈콘텐츠크리에이터', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/creator_tori/lv1.png'),
('콘텐츠크리에이터', '예술형(A)', 'A', 2, '실버콘텐츠크리에이터', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/creator_tori/lv2.png'),
('콘텐츠크리에이터', '예술형(A)', 'A', 3, '골드콘텐츠크리에이터', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/creator_tori/lv3.png'),
('콘텐츠크리에이터', '예술형(A)', 'A', 4, '다이아콘텐츠크리에이터', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/creator_tori/lv4.png'),
('콘텐츠크리에이터', '예술형(A)', 'A', 5, '마스터콘텐츠크리에이터', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/creator_tori/lv5.png'),
('파티시에', '예술형(A)', 'A', 1, '브론즈파티시에', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/patissier_tori/lv1.png'),
('파티시에', '예술형(A)', 'A', 2, '실버파티시에', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/patissier_tori/lv2.png'),
('파티시에', '예술형(A)', 'A', 3, '골드파티시에', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/patissier_tori/lv3.png'),
('파티시에', '예술형(A)', 'A', 4, '다이아파티시에', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/patissier_tori/lv4.png'),
('파티시에', '예술형(A)', 'A', 5, '마스터파티시에', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/A/patissier_tori/lv5.png'),
('과학수사관', '탐구형(I)', 'I', 1, '브론즈과학수사관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/forensic_investigator/lv1.png'),
('과학수사관', '탐구형(I)', 'I', 2, '실버과학수사관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/forensic_investigator/lv2.png'),
('과학수사관', '탐구형(I)', 'I', 3, '골드과학수사관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/forensic_investigator/lv3.png'),
('과학수사관', '탐구형(I)', 'I', 4, '다이아과학수사관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/forensic_investigator/lv4.png'),
('과학수사관', '탐구형(I)', 'I', 5, '마스터과학수사관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/forensic_investigator/lv5.png'),
('로봇공학자', '탐구형(I)', 'I', 1, '브론즈로봇공학자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/robotics_engineer/lv1.png'),
('로봇공학자', '탐구형(I)', 'I', 2, '실버로봇공학자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/robotics_engineer/lv2.png'),
('로봇공학자', '탐구형(I)', 'I', 3, '골드로봇공학자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/robotics_engineer/lv3.png'),
('로봇공학자', '탐구형(I)', 'I', 4, '다이아로봇공학자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/robotics_engineer/lv4.png'),
('로봇공학자', '탐구형(I)', 'I', 5, '마스터로봇공학자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/robotics_engineer/lv5.png'),
('생명과학연구원', '탐구형(I)', 'I', 1, '브론즈생명과학연구원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/bioscience_researcher/lv1.png'),
('생명과학연구원', '탐구형(I)', 'I', 2, '실버생명과학연구원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/bioscience_researcher/lv2.png'),
('생명과학연구원', '탐구형(I)', 'I', 3, '골드생명과학연구원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/bioscience_researcher/lv3.png'),
('생명과학연구원', '탐구형(I)', 'I', 4, '다이아생명과학연구원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/bioscience_researcher/lv4.png'),
('생명과학연구원', '탐구형(I)', 'I', 5, '마스터생명과학연구원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/bioscience_researcher/lv5.png'),
('소프트웨어개발자', '탐구형(I)', 'I', 1, '브론즈소프트웨어개발자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/software_developer/lv1.png'),
('소프트웨어개발자', '탐구형(I)', 'I', 2, '실버소프트웨어개발자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/software_developer/lv2.png'),
('소프트웨어개발자', '탐구형(I)', 'I', 3, '골드소프트웨어개발자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/software_developer/lv3.png'),
('소프트웨어개발자', '탐구형(I)', 'I', 4, '다이아소프트웨어개발자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/software_developer/lv4.png'),
('소프트웨어개발자', '탐구형(I)', 'I', 5, '마스터소프트웨어개발자', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/software_developer/lv5.png'),
('수의사', '탐구형(I)', 'I', 1, '브론즈수의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/veterinarian/lv1.png'),
('수의사', '탐구형(I)', 'I', 2, '실버수의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/veterinarian/lv2.png'),
('수의사', '탐구형(I)', 'I', 3, '골드수의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/veterinarian/lv3.png'),
('수의사', '탐구형(I)', 'I', 4, '다이아수의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/veterinarian/lv4.png'),
('수의사', '탐구형(I)', 'I', 5, '마스터수의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/veterinarian/lv5.png'),
('약사', '탐구형(I)', 'I', 1, '브론즈약사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/pharmacist/lv1.png'),
('약사', '탐구형(I)', 'I', 2, '실버약사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/pharmacist/lv2.png'),
('약사', '탐구형(I)', 'I', 3, '골드약사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/pharmacist/lv3.png'),
('약사', '탐구형(I)', 'I', 4, '다이아약사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/pharmacist/lv4.png'),
('약사', '탐구형(I)', 'I', 5, '마스터약사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/pharmacist/lv5.png'),
('의사', '탐구형(I)', 'I', 1, '브론즈의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/doctor/lv1.png'),
('의사', '탐구형(I)', 'I', 2, '실버의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/doctor/lv2.png'),
('의사', '탐구형(I)', 'I', 3, '골드의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/doctor/lv3.png'),
('의사', '탐구형(I)', 'I', 4, '다이아의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/doctor/lv4.png'),
('의사', '탐구형(I)', 'I', 5, '마스터의사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/doctor/lv5.png'),
('정보보안전문가', '탐구형(I)', 'I', 1, '브론즈정보보안전문가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/security_specialist/lv1.png'),
('정보보안전문가', '탐구형(I)', 'I', 2, '실버정보보안전문가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/security_specialist/lv2.png'),
('정보보안전문가', '탐구형(I)', 'I', 3, '골드정보보안전문가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/security_specialist/lv3.png'),
('정보보안전문가', '탐구형(I)', 'I', 4, '다이아정보보안전문가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/security_specialist/lv4.png'),
('정보보안전문가', '탐구형(I)', 'I', 5, '마스터정보보안전문가', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/I/security_specialist/lv5.png'),
('경찰', '현실형(R)', 'R', 1, '브론즈경찰', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/police_officer/lv1.png'),
('경찰', '현실형(R)', 'R', 2, '실버경찰', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/police_officer/lv2.png'),
('경찰', '현실형(R)', 'R', 3, '골드경찰', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/police_officer/lv3.png'),
('경찰', '현실형(R)', 'R', 4, '다이아경찰', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/police_officer/lv4.png'),
('경찰', '현실형(R)', 'R', 5, '마스터경찰', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/police_officer/lv5.png'),
('드론조종사', '현실형(R)', 'R', 1, '브론즈드론조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/drone_pilot/lv1.png'),
('드론조종사', '현실형(R)', 'R', 2, '실버드론조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/drone_pilot/lv2.png'),
('드론조종사', '현실형(R)', 'R', 3, '골드드론조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/drone_pilot/lv3.png'),
('드론조종사', '현실형(R)', 'R', 4, '다이아드론조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/drone_pilot/lv4.png'),
('드론조종사', '현실형(R)', 'R', 5, '마스터드론조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/drone_pilot/lv5.png'),
('반도체엔지니어', '현실형(R)', 'R', 1, '브론즈반도체엔지니어', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/semiconductor_engineer/lv1.png'),
('반도체엔지니어', '현실형(R)', 'R', 2, '실버반도체엔지니어', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/semiconductor_engineer/lv2.png'),
('반도체엔지니어', '현실형(R)', 'R', 3, '골드반도체엔지니어', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/semiconductor_engineer/lv3.png'),
('반도체엔지니어', '현실형(R)', 'R', 4, '다이아반도체엔지니어', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/semiconductor_engineer/lv4.png'),
('반도체엔지니어', '현실형(R)', 'R', 5, '마스터반도체엔지니어', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/semiconductor_engineer/lv5.png'),
('소방관', '현실형(R)', 'R', 1, '브론즈소방관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/firefighter/lv1.png'),
('소방관', '현실형(R)', 'R', 2, '실버소방관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/firefighter/lv2.png'),
('소방관', '현실형(R)', 'R', 3, '골드소방관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/firefighter/lv3.png'),
('소방관', '현실형(R)', 'R', 4, '다이아소방관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/firefighter/lv4.png'),
('소방관', '현실형(R)', 'R', 5, '마스터소방관', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/firefighter/lv5.png'),
('요리사', '현실형(R)', 'R', 1, '브론즈요리사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/chef/lv1.png'),
('요리사', '현실형(R)', 'R', 2, '실버요리사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/chef/lv2.png'),
('요리사', '현실형(R)', 'R', 3, '골드요리사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/chef/lv3.png'),
('요리사', '현실형(R)', 'R', 4, '다이아요리사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/chef/lv4.png'),
('요리사', '현실형(R)', 'R', 5, '마스터요리사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/chef/lv5.png'),
('자동차정비사', '현실형(R)', 'R', 1, '브론즈자동차정비사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/auto_mechanic/lv1.png'),
('자동차정비사', '현실형(R)', 'R', 2, '실버자동차정비사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/auto_mechanic/lv2.png'),
('자동차정비사', '현실형(R)', 'R', 3, '골드자동차정비사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/auto_mechanic/lv3.png'),
('자동차정비사', '현실형(R)', 'R', 4, '다이아자동차정비사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/auto_mechanic/lv4.png'),
('자동차정비사', '현실형(R)', 'R', 5, '마스터자동차정비사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/auto_mechanic/lv5.png'),
('전기기사', '현실형(R)', 'R', 1, '브론즈전기기사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/electrical_engineer/lv1.png'),
('전기기사', '현실형(R)', 'R', 2, '실버전기기사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/electrical_engineer/lv2.png'),
('전기기사', '현실형(R)', 'R', 3, '골드전기기사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/electrical_engineer/lv3.png'),
('전기기사', '현실형(R)', 'R', 4, '다이아전기기사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/electrical_engineer/lv4.png'),
('전기기사', '현실형(R)', 'R', 5, '마스터전기기사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/electrical_engineer/lv5.png'),
('항공기조종사', '현실형(R)', 'R', 1, '브론즈항공기조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/airline_pilot/lv1.png'),
('항공기조종사', '현실형(R)', 'R', 2, '실버항공기조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/airline_pilot/lv2.png'),
('항공기조종사', '현실형(R)', 'R', 3, '골드항공기조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/airline_pilot/lv3.png'),
('항공기조종사', '현실형(R)', 'R', 4, '다이아항공기조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/airline_pilot/lv4.png'),
('항공기조종사', '현실형(R)', 'R', 5, '마스터항공기조종사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/R/airline_pilot/lv5.png'),
('간호사', '사회형(S)', 'S', 1, '브론즈간호사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/nurse_ari/lv1.png'),
('간호사', '사회형(S)', 'S', 2, '실버간호사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/nurse_ari/lv2.png'),
('간호사', '사회형(S)', 'S', 3, '골드간호사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/nurse_ari/lv3.png'),
('간호사', '사회형(S)', 'S', 4, '다이아간호사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/nurse_ari/lv4.png'),
('간호사', '사회형(S)', 'S', 5, '마스터간호사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/nurse_ari/lv5.png'),
('사회복지사', '사회형(S)', 'S', 1, '브론즈사회복지사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/social_worker_ari/lv1.png'),
('사회복지사', '사회형(S)', 'S', 2, '실버사회복지사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/social_worker_ari/lv2.png'),
('사회복지사', '사회형(S)', 'S', 3, '골드사회복지사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/social_worker_ari/lv3.png'),
('사회복지사', '사회형(S)', 'S', 4, '다이아사회복지사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/social_worker_ari/lv4.png'),
('사회복지사', '사회형(S)', 'S', 5, '마스터사회복지사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/social_worker_ari/lv5.png'),
('승무원', '사회형(S)', 'S', 1, '브론즈승무원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/flight_attendant_tori/lv1.png'),
('승무원', '사회형(S)', 'S', 2, '실버승무원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/flight_attendant_tori/lv2.png'),
('승무원', '사회형(S)', 'S', 3, '골드승무원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/flight_attendant_tori/lv3.png'),
('승무원', '사회형(S)', 'S', 4, '다이아승무원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/flight_attendant_tori/lv4.png'),
('승무원', '사회형(S)', 'S', 5, '마스터승무원', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/flight_attendant_tori/lv5.png'),
('유치원교사', '사회형(S)', 'S', 1, '브론즈유치원교사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/kindergarten_teacher_tori/lv1.png'),
('유치원교사', '사회형(S)', 'S', 2, '실버유치원교사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/kindergarten_teacher_tori/lv2.png'),
('유치원교사', '사회형(S)', 'S', 3, '골드유치원교사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/kindergarten_teacher_tori/lv3.png'),
('유치원교사', '사회형(S)', 'S', 4, '다이아유치원교사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/kindergarten_teacher_tori/lv4.png'),
('유치원교사', '사회형(S)', 'S', 5, '마스터유치원교사', 'https://pydvuqjhzcrpauzpssxg.supabase.co/storage/v1/object/public/character-assets/S/kindergarten_teacher_tori/lv5.png');
