/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#7b5cf0",
        "primary-base": "#6240d5",
        "primary-container": "#7b5cf0",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        secondary: "#1daab4",
        "secondary-spot": "#006970",
        "secondary-container": "#7af1fc",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006e75",
        background: "#fbf8ff",
        point: "#f2effc",
        surface: "#fbf8ff",
        "surface-bright": "#fbf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f2fa",
        "surface-container": "#efedf5",
        "surface-container-high": "#e9e7ef",
        "surface-container-highest": "#e3e1e9",
        "surface-dim": "#dbd9e1",
        "surface-variant": "#e3e1e9",
        "input-fill": "#f7f5fd",
        "text-primary": "#1A1626",
        "text-muted": "#6E6A80",
        "on-surface": "#1a1b21",
        "on-surface-variant": "#484554",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        outline: "#797586",
        "outline-variant": "#cac4d7",
        "gradient-hero-start": "#8E70F7",
        "gradient-hero-end": "#6B45E4",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.75rem",
        xl: "2.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "16px",
        "container-padding": "24px",
        "card-gap": "24px",
      },
      fontFamily: {
        headline: ["'Hanken Grotesk'", "sans-serif"],
        body: ["'Be Vietnam Pro'", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      boxShadow: {
        "3d-base": "0px 4px 20px rgba(123, 92, 240, 0.05), 0px 2px 4px rgba(123, 92, 240, 0.02)",
        "3d-ambient": "0px 20px 40px rgba(123, 92, 240, 0.08)",
        "3d-hover": "0px 30px 50px rgba(123, 92, 240, 0.15), 0px 4px 8px rgba(123, 92, 240, 0.05)",
      },
    },
  },
  plugins: [],
}
