/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#6240d5",
        "primary-base": "#6240d5",
        "primary-container": "#7b5cf0",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#cbbeff",
        "primary-fixed": "#e6deff",
        "primary-fixed-dim": "#cbbeff",
        "on-primary-fixed": "#1d0061",
        "on-primary-fixed-variant": "#4a21be",

        secondary: "#006970",
        "secondary-spot": "#006970",
        "secondary-container": "#7af1fc",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006e75",
        "secondary-fixed": "#7ef4fe",
        "secondary-fixed-dim": "#5ed7e2",
        "on-secondary-fixed": "#002022",
        "on-secondary-fixed-variant": "#004f54",

        tertiary: "#5d5c67",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#767580",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#e4e1ee",
        "tertiary-fixed-dim": "#c7c5d1",
        "on-tertiary-fixed": "#1b1b24",
        "on-tertiary-fixed-variant": "#464650",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        background: "#fbf8ff",
        "on-background": "#1a1b21",
        surface: "#fbf8ff",
        "surface-dim": "#dbd9e1",
        "surface-bright": "#fbf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f2fa",
        "surface-container": "#efedf5",
        "surface-container-high": "#e9e7ef",
        "surface-container-highest": "#e3e1e9",
        "on-surface": "#1a1b21",
        "on-surface-variant": "#484554",
        "inverse-surface": "#2f3036",
        "inverse-on-surface": "#f2f0f8",
        "surface-variant": "#e3e1e9",
        "surface-tint": "#6341d6",
        "surface-white": "#FFFFFF",
        "input-fill": "#f7f5fd",
        point: "#f2effc",

        outline: "#797586",
        "outline-variant": "#cac4d7",
        
        "text-primary": "#1A1626",
        "text-muted": "#6E6A80",
        "gradient-hero-start": "#8E70F7",
        "gradient-hero-end": "#6B45E4",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "1rem",
        md: "0.75rem",
        lg: "1.75rem",
        xl: "2.5rem",
        "2xl": "2.8rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        base: "4px",
        gutter: "16px",
        "container-padding": "24px",
        "card-gap": "24px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        headline: ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "display-lg": ["'Hanken Grotesk'", "sans-serif"],
        body: ["'Be Vietnam Pro'", "sans-serif"],
        "body-md": ["'Be Vietnam Pro'", "sans-serif"],
        "body-lg": ["'Be Vietnam Pro'", "sans-serif"],
        "title-md": ["'Hanken Grotesk'", "sans-serif"],
        "label-sm": ["'Hanken Grotesk'", "sans-serif"],
        "label-lg": ["'Hanken Grotesk'", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      boxShadow: {
        "3d-base": "0px 4px 12px rgba(123, 92, 240, 0.05), 0px 20px 40px rgba(123, 92, 240, 0.1)",
        "3d-ambient": "0px 20px 40px rgba(123, 92, 240, 0.08)",
        "3d-lifted": "0px 8px 24px rgba(123, 92, 240, 0.1), 0px 32px 64px rgba(123, 92, 240, 0.15)",
        "3d-hover": "0px 30px 50px rgba(123, 92, 240, 0.15), 0px 4px 8px rgba(123, 92, 240, 0.05)",
      },
    },
  },
  plugins: [],
}
